# Read the Docs configuration file for QUBIX Documentation
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, set of tools, and environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "18"
  jobs:
    pre_create_environment:
      # Install dependencies in a virtual environment
      - asdf plugin-add nodejs
      - asdf install nodejs 18.17.0
      - asdf global nodejs 18.17.0
    post_checkout:
      # Generate documentation files from the main markdown
      - node generate-rtd-docs.js

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt

# Optional but recommended, declare the formats you want to build
formats:
  - pdf
  - htmlzip
  - epub
